/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartSkeleton: typeof import('./src/components/SkeletonScreen/CartSkeleton.vue')['default']
    CategorySkeleton: typeof import('./src/components/SkeletonScreen/CategorySkeleton.vue')['default']
    HomeSkeleton: typeof import('./src/components/SkeletonScreen/HomeSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
    UserSkeleton: typeof import('./src/components/SkeletonScreen/UserSkeleton.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanImage: typeof import('vant/es')['Image']
  }
}
